import { Product } from './api';

export const dummyProducts: Product[] = [
  {
    _id: '1',
    name: 'ZS-PA250 Professional Amplifier',
    slug: 'zs-pa250-professional-amplifier',
    family: 'Professional Audio',
    category: 'Amplifiers',
    technology: 'Class D',
    thumbnail: 'https://images.pexels.com/photos/7521047/pexels-photo-7521047.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/7521047/pexels-photo-7521047.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/6192297/pexels-photo-6192297.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1279813/pexels-photo-1279813.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    overview: 'The ZS-PA250 is a high-performance professional amplifier designed for commercial and residential applications. Featuring advanced Class D technology, it delivers exceptional sound quality with minimal power consumption.',
    keyHighlights: [
      '250W RMS Power Output',
      'Ultra-low distortion',
      'Built-in DSP processing',
      'Multiple input options',
      'Efficient cooling system',
    ],
    features: [
      'Professional-grade audio performance',
      'Remote control capability',
      'LED status indicators',
      'Thermal protection',
      'Short circuit protection',
      'Rack mountable design',
    ],
    applications: [
      'Conference rooms',
      'Auditoriums',
      'Retail stores',
      'Restaurants',
      'Hotels',
    ],
    idealFor: [
      'Professional installers',
      'Audio engineers',
      'System integrators',
    ],
    tags: ['amplifier', 'professional', 'class-d', 'high-power'],
    specifications: {
      powerOutput: '250W RMS @ 4Ω',
      channels: '2 Channels',
      inputChannels: '4 Mic/Line inputs',
      digitalPlayer: 'USB/SD Card',
      toneControl: {
        bass: '±12dB',
        mid: '±10dB',
        treble: '±12dB',
      },
      speakerOutput: '4-16Ω',
      frequencyResponse: '20Hz - 20kHz',
      snRatio: '>95dB',
      powerSupply: 'AC 220V 50Hz',
      dimensions: '482 x 88 x 350mm',
      weight: '8.5kg',
    },
    warranty: '2 years manufacturer warranty',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    _id: '2',
    name: 'ZS-MX120 Mixer Console',
    slug: 'zs-mx120-mixer-console',
    family: 'Studio Equipment',
    category: 'Mixers',
    technology: 'Analog',
    thumbnail: 'https://images.pexels.com/photos/7520408/pexels-photo-7520408.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/7520408/pexels-photo-7520408.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/7521047/pexels-photo-7521047.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    overview: 'The ZS-MX120 is a versatile 12-channel mixer console perfect for live sound reinforcement, recording studios, and broadcast applications. It offers premium preamps and comprehensive EQ controls.',
    keyHighlights: [
      '12 input channels',
      'Premium mic preamps',
      '3-band EQ per channel',
      'Built-in effects processor',
      'USB audio interface',
    ],
    features: [
      'Low-noise microphone preamps',
      '48V phantom power',
      'Aux sends and returns',
      'Monitor outputs',
      'Headphone output with level control',
      'Master LED metering',
    ],
    applications: [
      'Live performances',
      'Recording studios',
      'Podcasting',
      'Broadcasting',
      'Houses of worship',
    ],
    idealFor: [
      'Musicians',
      'Sound engineers',
      'Content creators',
    ],
    tags: ['mixer', 'analog', 'live-sound', 'studio'],
    specifications: {
      channels: '12 channels',
      inputChannels: '8 Mic/Line + 2 Stereo',
      frequencyResponse: '20Hz - 20kHz ±1dB',
      snRatio: '>100dB',
      powerSupply: 'AC 100-240V 50/60Hz',
      dimensions: '380 x 120 x 420mm',
      weight: '4.2kg',
    },
    warranty: '1 year manufacturer warranty',
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    _id: '3',
    name: 'ZS-SP800 Column Speaker System',
    slug: 'zs-sp800-column-speaker',
    family: 'Speaker Systems',
    category: 'Speakers',
    technology: 'Line Array',
    thumbnail: 'https://images.pexels.com/photos/3784221/pexels-photo-3784221.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/3784221/pexels-photo-3784221.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/164938/pexels-photo-164938.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    overview: 'The ZS-SP800 column speaker system delivers exceptional sound coverage with its innovative line array design. Perfect for venues requiring uniform sound distribution across large areas.',
    keyHighlights: [
      'Line array technology',
      '120-degree horizontal coverage',
      'Weather-resistant enclosure',
      '800W peak power handling',
      'Easy installation',
    ],
    features: [
      'Multiple mounting options',
      'Integrated crossover network',
      'High SPL capability',
      'Consistent frequency response',
      'Durable powder-coated finish',
    ],
    applications: [
      'Outdoor venues',
      'Sports facilities',
      'Shopping malls',
      'Transportation hubs',
      'Theme parks',
    ],
    idealFor: [
      'Commercial installations',
      'Event venues',
      'Public spaces',
    ],
    tags: ['speaker', 'column', 'line-array', 'commercial'],
    specifications: {
      powerOutput: '800W Peak, 400W RMS',
      speakerOutput: '8Ω',
      frequencyResponse: '60Hz - 18kHz',
      dimensions: '150 x 1200 x 150mm',
      weight: '12kg',
    },
    warranty: '2 years manufacturer warranty',
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
  },
  {
    _id: '4',
    name: 'ZS-WM500 Wireless Microphone System',
    slug: 'zs-wm500-wireless-mic',
    family: 'Wireless Audio',
    category: 'Microphones',
    technology: 'UHF',
    thumbnail: 'https://images.pexels.com/photos/7521359/pexels-photo-7521359.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/7521359/pexels-photo-7521359.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1751731/pexels-photo-1751731.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    overview: 'Professional UHF wireless microphone system with exceptional audio quality and reliable performance. Features automatic frequency scanning and IR synchronization for easy setup.',
    keyHighlights: [
      'UHF frequency band',
      'Automatic frequency scanning',
      'IR sync technology',
      '100m operating range',
      'Rechargeable batteries',
    ],
    features: [
      'True diversity reception',
      'LCD display with signal strength',
      'Mute function',
      'Low battery indicator',
      'Adjustable squelch control',
      'Balanced XLR output',
    ],
    applications: [
      'Live performances',
      'Presentations',
      'Corporate events',
      'Education',
      'Houses of worship',
    ],
    idealFor: [
      'Performers',
      'Presenters',
      'Educators',
    ],
    tags: ['wireless', 'microphone', 'uhf', 'handheld'],
    specifications: {
      frequencyResponse: '50Hz - 15kHz',
      snRatio: '>105dB',
      powerSupply: 'DC 12V / Rechargeable batteries',
      dimensions: 'Receiver: 210 x 45 x 180mm',
      weight: 'Receiver: 1.2kg, Handheld: 280g',
    },
    warranty: '1 year manufacturer warranty',
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-02-10T10:00:00Z',
  },
  {
    _id: '5',
    name: 'ZS-SUB15 Powered Subwoofer',
    slug: 'zs-sub15-powered-subwoofer',
    family: 'Bass Systems',
    category: 'Subwoofers',
    technology: 'Active',
    thumbnail: 'https://images.pexels.com/photos/6192565/pexels-photo-6192565.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/6192565/pexels-photo-6192565.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/3784221/pexels-photo-3784221.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    overview: 'High-performance 15-inch powered subwoofer designed to deliver deep, powerful bass. Built-in amplifier and advanced DSP ensure optimal performance in any setting.',
    keyHighlights: [
      '15-inch long-excursion driver',
      '1000W Class D amplifier',
      'Built-in DSP',
      'Variable crossover',
      'Multiple input options',
    ],
    features: [
      'Solid wood cabinet construction',
      'Port design for extended bass',
      'Phase control switch',
      'Ground lift switch',
      'Heavy-duty steel grille',
      'Pole mount socket',
    ],
    applications: [
      'Live sound reinforcement',
      'DJ setups',
      'Night clubs',
      'Concert venues',
      'Mobile entertainment',
    ],
    idealFor: [
      'DJs',
      'Live sound professionals',
      'Venue owners',
    ],
    tags: ['subwoofer', 'powered', 'bass', 'active'],
    specifications: {
      powerOutput: '1000W Peak, 500W RMS',
      speakerOutput: '4Ω',
      frequencyResponse: '35Hz - 150Hz',
      powerSupply: 'AC 220V 50/60Hz',
      dimensions: '480 x 560 x 540mm',
      weight: '28kg',
    },
    warranty: '2 years manufacturer warranty',
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
  },
  {
    _id: '6',
    name: 'ZS-DA60 Digital Audio Processor',
    slug: 'zs-da60-digital-processor',
    family: 'Signal Processing',
    category: 'Processors',
    technology: 'DSP',
    thumbnail: 'https://images.pexels.com/photos/1279813/pexels-photo-1279813.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1279813/pexels-photo-1279813.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/442540/pexels-photo-442540.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    overview: 'Advanced digital audio processor with 6 inputs and 6 outputs. Features comprehensive EQ, dynamics, and delay processing for professional sound system optimization.',
    keyHighlights: [
      '6 x 6 matrix configuration',
      'Parametric EQ on all channels',
      'Limiter and compressor',
      'Adjustable delay up to 1000ms',
      'PC control software',
    ],
    features: [
      '48kHz/24-bit processing',
      'Multiple presets storage',
      'Real-time monitoring',
      'RS-232 and USB control',
      'Lockable front panel',
      'Balanced XLR and terminal block I/O',
    ],
    applications: [
      'System tuning',
      'Zone management',
      'Feedback suppression',
      'Speaker alignment',
      'Multi-room audio',
    ],
    idealFor: [
      'System integrators',
      'Installation professionals',
      'Audio consultants',
    ],
    tags: ['processor', 'dsp', 'digital', 'system-optimization'],
    specifications: {
      inputChannels: '6 balanced inputs',
      frequencyResponse: '20Hz - 20kHz ±0.5dB',
      snRatio: '>110dB',
      powerSupply: 'AC 100-240V 50/60Hz',
      dimensions: '482 x 44 x 240mm',
      weight: '2.8kg',
    },
    warranty: '2 years manufacturer warranty',
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-02-20T10:00:00Z',
  },
];
